version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    environment:
      FLASK_ENV: production
